### ISSUE TITLE
Documentation broken links

### ISSUE THREAD

**Issue by colehorsman** [PaloAltoNetworks/Prisma-Enhanced-Remediation#21]
## Documentation link ->
https://github.com/PaloAltoNetworks/Prisma-Enhanced-Remediation/blob/master/AWS/lambda_package/runbook_details.md.md#aws-security-groups-allow-internet-traffic-to-ssh-port-22
https://github.com/PaloAltoNetworks/Prisma-Enhanced-Remediation/blob/master/AWS/lambda_package/runbook_details.md.md#aws-security-groups-allow-internet-traffic-from-internet-to-telnet-port-23
https://github.com/PaloAltoNetworks/Prisma-Enhanced-Remediation/blob/master/AWS/lambda_package/runbook_details.md.md#aws-security-groups-allow-internet-traffic-from-internet-to-rdp-port-3389

 
https://github.com/PaloAltoNetworks/Prisma-Enhanced-Remediation/blob/master/AWS/lambda_package/README.md

## Describe the problem

all above links point to 404 and should point to:

AWS Security Groups allow internet traffic to SSH port (22)
Script name: AWS-EC2-002.py
Prisma Cloud policy descriptor: PC-AWS-VPC-23
Runbook summary: Removes EC2 security group rules containing global access to TCP port 22 (SSH).
Required IAM permissions:
ec2:DescribeSecurityGroups
ec2:RevokeSecurityGroupIngress
CIS section: 4.1
Caveats: N/A

**Comment by youngleepanw** [comment]
Thanks so much @colehorsman for the catch! I've updated the links accordingly.

**Comment by colehorsman** [comment]
I should be thanking you for your work on this repo - saving me a ton of
time and effort. I will continue to ping you if i see things as i sort
through the repo. I am assuming your work for Palo Alto, right? Im planning
to customize a few of these and have soem ideas on new controls to
implement. would love to work with you on this as I get further into it!

Best,
Cole Horsman
colehorsman@gmail.com | 515.577.1004

**Comment by youngleepanw** [comment]
Hey Cole,

Yes! I do work at Palo Alto Networks. I'm glad to hear this feature has been coming in handy for you. Please feel free to email me at ylee@paloaltonetworks.com with your ideas and I'd be happy to get your feedback on how we can make this feature even better.

Sincerely,

Young
